[package]
name = "enumeration"
version = "0.1.0"
description = "Add-only set of blobs with numbering and two-way lookup storing blobs in regions"
repository = "https://github.com/research-ag/enumeration"
keywords = [ "set", "bijective", "map", "lookup", "key", "stable" ]
license = "Apache-2.0"

[dependencies]
test = "1.2.0"
base = "0.10.3"
btree = "https://github.com/research-ag/MotokoStableBTree#main@44d80831198dfb8be50f9a069fbfe5ee224d30ce"

[toolchain]
moc = "0.10.3"
wasmtime = "16.0.0"
